[package]
name = "rain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Command Line Parsing
structopt = "0.3.25"

# Parse Images
image = "0.23.14"
